---

ELASTIC_CONTAINER_NAME: "odfe-cauldron"

ELASTIC_PORT: '9200'

ELASTIC_PROTOCOL: 'https'

ELASTIC_IMAGE_BUILD_DIR: "{{ CAULDRON_CONFIG_DIR }}/elastic-build"
ELASTIC_IMAGE_DOCKERFILE_PATH: "../docker/opendistro/"