---

- set_fact:
    container_list:
      - "{{ db_container_name }}"
      - "{{ ELASTIC_CONTAINER_NAME }}"
      - "{{ KIBANA_CONTAINER_NAME }}"
      - "{{ django_container_name }}"
      - "{{ nginx_container_name }}"

- include_tasks: container_status.yml
  loop: "{{ container_list }}"
  loop_control:
    loop_var: container_name

- include_tasks: container_status.yml
  loop: "{{ range(0, NUM_WORKERS) | list | map('regex_replace', '^(.*)$', worker_name + '_\\1') | list }}"
  loop_control:
    loop_var: container_name
