---

- name: Kill container <{{ container_name }}>
  docker_container:
    name: "{{ container_name }}"
    state: stopped
    force_kill: yes

- name: Get container <{{ container_name }}> status
  shell: docker ps -a -f name={{ container_name }} --format {%raw%}"table {{.Status}}"{%endraw%} | awk 'FNR == 2 {print}' | awk '{print $1}'
  register: status

- name: Check container <{{ container_name }}> is not running
  assert:
    that:
      - "status.stdout == 'Exited'"
    msg: "status is '{{status.stdout}}'"
