---
- name: "Ensures {{CAULDRON_CONFIG_DIR}}/worker dir exists"
  file:
    path: "{{CAULDRON_CONFIG_DIR}}/worker"
    state: directory
    recurse: yes
  tags: [worker]

- name: "Create setup.cfg for sirmordred {{ HATSTALL_ENABLED | ternary('with Hatstall', '') }}"
  template:
    src: "{{ HATSTALL_ENABLED | ternary('setup-hatstall.cfg.j2', 'setup.cfg.j2') }}"
    dest: "{{ CAULDRON_CONFIG_DIR }}/worker/setup.cfg"
  tags: [worker]
