---

- name: "Ensures {{ CAULDRON_CONFIG_DIR }}/jwt_key/ dir exists"
  file:
    path: "{{ CAULDRON_CONFIG_DIR }}/jwt_key"
    recurse:  yes
    state: directory
  tags: [django, elastic]


- name: "Private JSON Web Token key for Django"
  shell: "ssh-keygen -q -t rsa -b 4096 -f {{ CAULDRON_CONFIG_DIR }}/jwt_key/jwtR256.key -N '' -C '' -m pem"
  args:
    creates: "{{ CAULDRON_CONFIG_DIR }}/jwt_key/jwtR256.key"
  tags: [django, elastic]


- name: "Public JSON Web Token key for Elastic"
  shell: "openssl rsa -in {{ CAULDRON_CONFIG_DIR }}/jwt_key/jwtR256.key -pubout -out {{ CAULDRON_CONFIG_DIR }}/jwt_key/pub.jwtR256.key"
  args:
    creates: "{{ CAULDRON_CONFIG_DIR }}/jwt_key/pub.jwtR256.key"
  tags: [django, elastic]
  register: public_jwt_result


- name: "Format the JSON Web Token public key for Elastic"
  shell: "sed '1d' {{ CAULDRON_CONFIG_DIR }}/jwt_key/pub.jwtR256.key | sed '$d' | tr -d '\n'"
  register: "es_jwt_signing_key"
  tags: [django, elastic]
