#!/usr/bin/env python3

"""
List files available at S3 bucket in a specific path
Remove older than 7 days
"""

import os
import datetime
import boto3

LIMIT_DATE = datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(days=7)


S3_ENDPOINT = os.getenv('S3_ENDPOINT')
S3_BUCKET = os.getenv('S3_BUCKET')
S3_ACCESS_KEY = os.getenv('S3_ACCESS_KEY')
S3_SECRET_KEY = os.getenv('S3_SECRET_KEY')
S3_PATH = os.getenv('S3_PATH')


objects = []
session = boto3.session.Session()
client = session.client('s3',
                        endpoint_url=f'https://{S3_ENDPOINT}',
                        aws_access_key_id=S3_ACCESS_KEY,
                        aws_secret_access_key=S3_SECRET_KEY)

response = client.list_objects(Bucket=S3_BUCKET,
                               Prefix=f"{S3_PATH}/mysqldump",
                               )
for obj in response.get('Contents', []):
    if obj['LastModified'] <= LIMIT_DATE:
        objects.append({'Key': obj['Key']})

objects = objects[:1000]
client.delete_objects(Bucket=S3_BUCKET, Delete={'Objects': objects})
