---

# Generate hashes for each item in `<loop_psw>` and store the result in a variable
- name: Generate hash for {{item.loop_output}} password
  shell: "{{ CAULDRON_CONFIG_DIR }}/bcrypt-env/bin/python -c 'import bcrypt; print(bcrypt.hashpw(b\"{{ item.loop_psw }}\", bcrypt.gensalt()).decode())'"
  register: output
  tags: [elastic]

- set_fact:
    "{{ item.loop_output }}": "{{ output.stdout }}"
  tags: [elastic]
