---

- name: Run ElasticSearch
  docker_container:
    name: "{{ ELASTIC_CONTAINER_NAME }}"
    image: "{{ ELASTIC_IMAGE_NAME }}"
    state: started
    restart_policy: "always"
    networks:
      - name: "{{ NETWORK_NAME }}"
    ulimits:
      - 'memlock:-1:-1'
    env:
      ES_JAVA_OPTS: "-Xms{{ELASTIC_MEMORY}} -Xmx{{ELASTIC_MEMORY}}"

    volumes:
      - "{{ELASTIC_MOUNT_POINT}}:/usr/share/elasticsearch/data"
      - "{{CAULDRON_CONFIG_DIR}}/es/keys/root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem"

      - "{{CAULDRON_CONFIG_DIR}}/es/keys/node-1.pem:/usr/share/elasticsearch/config/node-1.pem"
      - "{{CAULDRON_CONFIG_DIR}}/es/keys/node-1-key.pem:/usr/share/elasticsearch/config/node-1-key.pem"

      - "{{CAULDRON_CONFIG_DIR}}/es/keys/admin.pem:/usr/share/elasticsearch/config/admin.pem"
      - "{{CAULDRON_CONFIG_DIR}}/es/keys/admin-key.pem:/usr/share/elasticsearch/config/admin-key.pem"

      - "{{CAULDRON_CONFIG_DIR}}/es/elasticsearch-secured.yml:/usr/share/elasticsearch/config/elasticsearch.yml"

      - "{{CAULDRON_CONFIG_DIR}}/es/internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml"
      - "{{CAULDRON_CONFIG_DIR}}/es/opendistro-config.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml"
  tags: [elastic]

- name: Check if there are indices created for initializing Security index
  command: "docker exec {{ ELASTIC_CONTAINER_NAME }} test -d /usr/share/elasticsearch/data/nodes/0/indices"
  register: es_indices_output
  ignore_errors: True
  changed_when: False
  tags: [elastic]

- name: Permission to execute securityadmin for Elastic Search
  command: "docker exec {{ ELASTIC_CONTAINER_NAME }} chmod +x 'plugins/opendistro_security/tools/securityadmin.sh'"
  when: es_indices_output.rc == 1
  tags: [elastic]

- name: Run securityadmin to initialize Open Distro Security (wait for Elastic running)
  command: "docker exec {{ ELASTIC_CONTAINER_NAME }} plugins/opendistro_security/tools/securityadmin.sh -cd plugins/opendistro_security/securityconfig/ -cacert config/root-ca.pem -cert config/admin.pem -key config/admin-key.pem -icl -nhnv"
  register: securityadmin_result
  until: securityadmin_result.rc == 0
  retries: 10
  delay: 5
  when: es_indices_output.rc == 1
  tags: [elastic]

- name: Set the default template to 1 shard and 0 replicas per index
  command: "docker exec {{ ELASTIC_CONTAINER_NAME}} curl -XPOST -k -H \"Content-type: application/json\" \"https://admin:{{ELASTIC_ADMIN_PASSWORD}}@elastic_service:9200/_template/default\" -d '{\"template\": \"*\", \"order\": -1, \"settings\": { \"number_of_shards\": \"1\", \"number_of_replicas\": \"0\"}}'"
  tags: [elastic]
