---

# This inventory setup is prepared for a local Cauldron deployment.
# For other types of deployment, please refer to the documentation.

all:
  hosts:
    cauldron_host:
      # Location of the host: localhost, IP or domain
      ansible_host: localhost
      # Type of connection: ssh or local
      ansible_connection: local
      # User used for the remote location
      # ansible_ssh_user:
      ansible_python_interpreter: /usr/bin/python3
  children:
    cauldron_group:
      hosts:
        cauldron_host
    elastic_group:
      hosts:
        cauldron_host
    database_group:
      hosts:
        cauldron_host
