---

- name: Run syslog-ng container
  docker_container:
    name: "{{ SYSLOG_CONTAINER_NAME }}"
    image: "{{ SYSLOG_IMAGE_NAME }}"
    state: started
    restart_policy: "always"
    env:
      MATOMO_USER: "{{MATOMO_USER}}"
      MATOMO_PASSWORD: "{{MATOMO_PASSWORD}}"
      MATOMO_URL: "http://{{MATOMO_CONTAINER_NAME}}"
    networks:
      - name: "{{ NETWORK_NAME }}"
    volumes:
      - "{{ SYSLOG_MOUNT_POINT }}:/var/log/syslog"
  tags: [syslog]
