---

- name: Run syslog-ng container
  docker_container:
    name: "{{ SYSLOG_CONTAINER_NAME }}"
    image: "{{ SYSLOG_IMAGE_NAME }}"
    state: started
    command: "--no-caps"
    restart_policy: "always"
    env:
      ELASTIC_HOST: "{{ ELASTIC_HOST }}"
      ELASTIC_PASSWORD: "{{ ELASTIC_ADMIN_PASSWORD }}"
    networks:
      - name: "{{ NETWORK_NAME }}"
    volumes:
      - "{{CAULDRON_CONFIG_DIR}}/syslog/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf"
      - "{{ SYSLOG_MOUNT_POINT }}:/var/log/syslog"
  tags: [syslog]
