---

- name: Run Matomo container
  docker_container:
    name: "{{ MATOMO_CONTAINER_NAME }}"
    image: "{{ MATOMO_IMAGE_NAME }}"
    state: started
    restart_policy: "always"
    env:
      MATOMO_DATABASE_HOST: "db_cauldron_service"
      MATOMO_DATABASE_ADAPTER: "mysql"
      MATOMO_DATABASE_USERNAME: "{{DB_MATOMO_USER}}"
      MATOMO_DATABASE_PASSWORD: "{{DB_MATOMO_PASSWORD}}"
      MATOMO_DATABASE_DBNAME: "{{DB_MATOMO_NAME}}"
      MATOMO_DATABASE_TABLES_PREFIX: "matomo_"

    networks:
      - name: "{{ NETWORK_NAME }}"
    ports: ["8080:80"]
    volumes:
      - "{{ MATOMO_MOUNT_POINT }}:/var/www/html"
      - "{{CAULDRON_CONFIG_DIR}}/matomo/apache.conf:/etc/apache2/conf-enabled/apache.conf"
  tags: [matomo]
