---
################### DOCKER IMAGES #####################
WEB_IMAGE_NAME: "cauldronio/webserver:latest"
WORKER_IMAGE_NAME: "cauldronio/poolsched:latest"
ODFE_CONFIG_IMAGE_NAME: "cauldronio/odfe-config:latest"
PA_TO_ES_IMAGE_NAME: "cauldronio/pa-to-es:latest"
ELASTIC_IMAGE_NAME: "amazon/opendistro-for-elasticsearch:1.11.0"
KIBANA_IMAGE_NAME: "amazon/opendistro-for-elasticsearch-kibana:1.11.0"
SYSLOG_IMAGE_NAME: "cauldronio/syslog-ng:latest"
MATOMO_IMAGE_NAME: "matomo:3"
DB_IMAGE_NAME: "mariadb:10.5"


#################### APPLICATION KEYS ####################
# GitHub Oauth App keys
gh_client_id: ""
gh_client_secret: ""

# Gitlab Oauth App keys
gl_client_id: ""
gl_client_secret: ""

# Meetup Oauth App keys
meetup_client_id: ""
meetup_client_secret: ""

# Gnome Oauth App keys
gnome_client_id: ""
gnome_client_secret: ""

# KDE Oauth App keys
kde_client_id: ""
kde_client_secret: ""

# Twitter Oauth App keys
twitter_client_id: ""
twitter_client_secret: ""

# StackExchange App keys
stackexchange_client_id: ""
stackexchange_client_secret: ""
stackexchange_app_key: ""

#################### BASE CONFIGURATION ####################
CAULDRON_CONFIG_DIR: "/tmp/cauldron-data"

# If enabled, Grimoirelab will use Sortinghat and fetch GitHub users information.
HATSTALL_ENABLED: false

# If enabled, some metrics will be collected from Performance Analyzer and stored in Elasticsearch.
PA_TO_ES_ENABLED: false

# If enabled, run a new container with Matomo for metrics. It should be manually configured
MATOMO_ENABLED: false

# Number of mordred worker. Use ~15/20 for production.
NUM_WORKERS: 5

# Public IP address to access Cauldron (or localhost for local deployments)
CAULDRON_HOST: "localhost"

# IP address where the Django service is hosted (or container name for single-host deployments)
WEB_HOST: "cauldron_service"

# IP address where the Django database service is hosted (or container name for single-host deployments)
DB_HOST: "db_cauldron_service"

# IP address where the Elasticsearch service is hosted (or container name for single-host deployments)
ELASTIC_HOST: "odfe-cauldron"

# IP address where the Kibana service is hosted (or container name for single-host deployments)
KIBANA_HOST: "kibana-cauldron"

# Port where the APP will be available. Use 443 for production
CAULDRON_PORT: 9000

# Port where Matomo will be running
MATOMO_PORT: 9001

# Enable port 80 for redirecting to https. Use true for production
ENABLE_PORT_80: false

# Host (Keep same as deployed) All accepted here
DJANGO_HOSTS: "*"

# Increase in production
ELASTIC_MEMORY: "4g"

# Write your Google Analytics ID if you want it enabled
GOOGLE_ANALYTICS_ID: ""

# If enabled, Plausible Analytics will start to analyze site activity (You need to configure the domain in https://plausible.io/)
PLAUSIBLE_ANALYTICS_ENABLED: false

# Plausible Analytics Dashboard URL
PLAUSIBLE_ANALYTICS_URL: ""


#################### PASSWORDS #######################
DB_USER_PASSWORD: "test-password"
DB_MATOMO_PASSWORD: "test-password"

# Use the same User and Password when you configure Matomo the first time
MATOMO_USER: "cauldron"
MATOMO_PASSWORD: "test-password"

ELASTIC_ADMIN_PASSWORD: "test-password"
ELASTIC_LOGSTASH_PASSWORD: "test-password"
ELASTIC_KIBANASERVER_PASSWORD: "test-password"
ELASTIC_KIBANARO_PASSWORD: "test-password"
ELASTIC_READALL_PASSWORD: "test-password"
ELASTIC_SNAPSHOTRESTORE_PASSWORD: "test-password"


################## DOCKER MOUNT POINT #####################
# Could be either a path or a Docker volume
DB_MOUNT_POINT: "database_volume"
PROJECT_LOGS_MOUNT_POINT: "cauldron_logs_volume"
ELASTIC_MOUNT_POINT: "elastic_data_volume"
ELASTIC_SNAPSHOT_MOUNT_POINT: "elastic_snapshots"
PERCEVAL_REPOS_MOUNT_POINT: "perceval_repos"
SYSLOG_MOUNT_POINT: "syslog_volume"
MATOMO_MOUNT_POINT: "matomo_volume"
NGINX_STATIC_FILES_MOUNT_POINT: "static_files_volume"


#################### DOCKER NAMES ####################
# Do not change the names unless you know what are you doing
DB_CONTAINER_NAME: "db_cauldron_service"
WEB_CONTAINER_NAME: "cauldron_service"
WORKER_CONTAINER_NAME: "sched_worker" # A number will be appended eg. sched_worker_1
ELASTIC_CONTAINER_NAME: "odfe-cauldron" # NEVER change it
KIBANA_CONTAINER_NAME: "kibana-cauldron"
NGINX_CONTAINER_NAME: "nginx_service"
SYSLOG_CONTAINER_NAME: 'syslog_service'
ODFE_CONFIG_CONTAINER_NAME: "odfe_config_cauldron"
MATOMO_CONTAINER_NAME: "matomo_service"
PA_TO_ES_CONTAINER_NAME: "pa-to-es"
WORKER_IDENTITIES_CONTAINER_NAME: "worker_identities"

NETWORK_NAME: "network_cauldron"


#################### ADMINS ####################
# GitHub Admins
GITHUB_ADMINS: []

# Gitlab Admins
GITLAB_ADMINS: []

# Meetup Admins
MEETUP_ADMINS: []

# Gnome Admins
GNOME_ADMINS: []

# KDE Admins
KDE_ADMINS: []

# Twitter Admins
TWITTER_ADMINS: []

# Stack Admins
STACK_EXCHANGE_ADMINS: []

LIMITED_ACCESS: false


####################  DEVELOPMENT ####################

### RUN YOUR LOCAL CODE ###
DEV_ENABLED: False
DEV_WEBSERVER_REPOSITORY: ""
DEV_POOLSCHED_REPOSITORY: ""
DEV_COMMON_APPS_REPOSITORY: ""
DEV_WORKER_REPOSITORY: ""


### BUILD IMAGES ###
# If you don't define a local path for the code, the image will be built from the master branch

# WEB_IMAGE_LOCAL_CODE: ""
# WORKER_IMAGE_LOCAL_CODE: ""
