---

KIBANA_CONTAINER_NAME: "kibana-cauldron"

KIBANA_PORT: '5601'

KIBANA_PROTOCOL: 'http'

KIBANA_URL_PATH: '/kibana'

ELASTIC_PORT: '9200'

KIBANA_EXPORTED_PORTS: "{{KIBANA_HOST}}:{{KIBANA_PORT}}:{{KIBANA_PORT}}"
