---

- name: Run NGINX
  vars:
    conditional_ports:
      - name: cauldron
        mapping: "{{ CAULDRON_PORT }}:{{ CAULDRON_PORT }}"
        enabled: true
      - name: matomo
        mapping: "{{ MATOMO_PORT }}:{{ MATOMO_PORT }}"
        enabled: "{{ MATOMO_ENABLED }}"
      - name: port80
        mapping: "80:80"
        enabled: "{{ ENABLE_PORT_80 }}"
  docker_container:
    name: "{{ NGINX_CONTAINER_NAME }}"
    image: "{{ NGINX_IMAGE_NAME }}"
    state: started
    restart_policy: "always"
    networks:
      - name: "{{ NETWORK_NAME }}"
    ports: "{{ conditional_ports | selectattr('enabled', 'equalto', true) | map(attribute='mapping') | list }}"
    volumes:
      - "{{CAULDRON_CONFIG_DIR}}/nginx/nginx_cauldron.conf:/etc/nginx/conf.d/nginx_cauldron.conf"
      - "{{CAULDRON_CONFIG_DIR}}/nginx/certificates:/certificates"
  tags: [nginx]
