---
################### DOCKER IMAGES #####################
DB_IMAGE_NAME: "cauldronio/database:latest"
WEB_IMAGE_NAME: "cauldronio/webserver:latest"
WORKER_IMAGE_NAME: "cauldronio/worker:latest"
PANELS_IMAGE_NAME: "cauldronio/panels:latest"
HATSTALL_IMAGE_NAME: "grimoirelab/hatstall:latest"
ELASTIC_IMAGE_NAME: "amazon/opendistro-for-elasticsearch:1.2.0"
KIBANA_IMAGE_NAME: "amazon/opendistro-for-elasticsearch-kibana:1.2.0"


#################### APPLICATION KEYS ####################
# GitHub Oauth App keys
gh_client_id: ""
gh_client_secret: ""

# Gitlab Oauth App keys
gl_client_id: ""
gl_client_secret: ""

# Meetup Oauth App keys
meetup_client_id: ""
meetup_client_secret: ""


#################### BASE CONFIGURATION ####################
CAULDRON_CONFIG_DIR: "/tmp/cauldron-data"

# If enabled, Grimoirelab will use Sortinghat and fetch GitHub users information.
HATSTALL_ENABLED: false

# Number of mordred worker. Use ~15/20 for production.
NUM_WORKERS: 5

# Port where the APP will be available. Use 443 for production
CAULDRON_PORT: 9000

# Port where Hatstall will be available.
HATSTALL_PORT: 9001

# Enable port 80 for redirecting to https. Use true for production
ENABLE_PORT_80: false

# Host (Keep same as deployed) All accepted here
DJANGO_HOSTS: "*"

# Increase in production
ELASTIC_MEMORY: "4g"

# Write your Google Analytics ID if you want it enabled
GOOGLE_ANALYTICS_ID: ""


#################### PASSWORDS #######################
DB_USER_PASSWORD: "test-password"

ELASTIC_ADMIN_PASSWORD: "test-password"
ELASTIC_LOGSTASH_PASSWORD: "test-password"
ELASTIC_KIBANASERVER_PASSWORD: "test-password"
ELASTIC_KIBANARO_PASSWORD: "test-password"
ELASTIC_READALL_PASSWORD: "test-password"
ELASTIC_SNAPSHOTRESTORE_PASSWORD: "test-password"

HATSTALL_USER: "cauldron"
HATSTALL_PASSWORD: "test-password"


################## DOCKER MOUNT POINT #####################
# Could be either a path or a Docker volume
DB_MOUNT_POINT: "database_volume"
LOGS_MOUNT_POINT: "cauldron_logs_volume"
ELASTIC_MOUNT_POINT: "elastic_data_volume"
ELASTIC_SNAPSHOT_MOUNT_POINT: "elastic_snapshots"
PERCEVAL_REPOS_MOUNT_POINT: "perceval_repos"
HATSTALL_DB_MOUNT_POINT: "hatstall_db"


#################### DOCKER NAMES ####################
# Do not change the names unless you know what are you doing
DB_CONTAINER_NAME: "db_cauldron_service"
WEB_CONTAINER_NAME: "cauldron_service"
WORKER_CONTAINER_NAME: "worker_service" # A number will be appended eg. worker_service_1
ELASTIC_CONTAINER_NAME: "elastic_service" # NEVER change it
KIBANA_CONTAINER_NAME: "kibana_service"
NGINX_CONTAINER_NAME: 'nginx_service'
PANELS_CONTAINER_NAME: "panels_cauldron"
HATSTALL_CONTAINER_NAME: "hatstall"

NETWORK_NAME: "network_cauldron"


####################  DEVELOPMENT ####################

### RUN YOUR LOCAL CODE ###
# (Only dev) WEB_MOUNT_CODE: "/home/user/src/cauldron-web"
# (Only dev) WORKER_MOUNT_CODE: "/home/user/src/cauldron-web"


### BUILD IMAGES ###
# If you don't define a local path for the code, the image with be built with the master branch

# WEB_IMAGE_LOCAL_CODE: ""
# WORKER_IMAGE_LOCAL_CODE: ""
