---

- name: Run Hatstall
  docker_container:
    name: "{{ HATSTALL_CONTAINER_NAME }}"
    image: "{{ HATSTALL_IMAGE_NAME }}"
    state: started
    restart_policy: "always"
    env:
      DATABASE_DIR: "/db/"
      ADMIN_USER: "{{ HATSTALL_USER }}"
      ADMIN_PASS: "{{ HATSTALL_PASSWORD }}"
    networks:
      - name: "{{ NETWORK_NAME }}"
    volumes:
      - "{{CAULDRON_CONFIG_DIR}}/hatstall/shdb.cfg:/home/grimoirelab/shdb.cfg"
      - "{{CAULDRON_CONFIG_DIR}}/hatstall/apache-hatstall.conf:/home/grimoirelab/apache-hatstall.conf"
      - "{{HATSTALL_DB_MOUNT_POINT}}:/db"
  tags: [hatstall]
