---

- name: Ensures {{CAULDRON_CONFIG_DIR}}/hatstall dir exists
  file:
    path: "{{CAULDRON_CONFIG_DIR}}/hatstall"
    state: directory
    recurse: yes
  tags: [hatstall]


- name: Hatstall database configuration
  template:
    src: shdb.cfg.j2
    dest: "{{ CAULDRON_CONFIG_DIR }}/hatstall/shdb.cfg"
    mode: 0644
  tags: [hatstall]


- name: Hatstall script installation
  copy:
    src: hatstall_installation.sh
    dest: "{{ CAULDRON_CONFIG_DIR }}/hatstall/hatstall_installation.sh"
    mode: 0644
  tags: [hatstall]
