---
# Load default Kibana panels into Elasticsearch
#   (needs Kibana up and running, so first wait for it)

- name: Wait until Kibana is done starting
  uri:
    url: "https://{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}:{{app_port}}/kibana"
    method: GET
    validate_certs: no
  register: result
  until: result.status == 200
  retries: 10
  delay: 5

# The panels container will load default Kibana paneles into Elasticsearch,
#   and will be auto removed afterwards.
- name: "Load default panels (may take some time): {{panels_container}}"
  docker_container:
    name: "{{panels_container}}"
    image: "{{panels_image}}"
    state: started
    auto_remove: true
    restart: true
    detach: no
    networks:
      - name: "{{ network_name }}"
    volumes:
      - "{{configuration_dir}}/archimedes_panels/settings.py:/settings.py"

