---

- name: Import default panels
  docker_container:
    name: "{{panels_container}}"
    image: "{{panels_image}}"
    state: started
    networks:
      - name: "{{ network_name }}"
    volumes:
      - "{{configuration_dir}}/archimedes_panels/settings.py:/settings.py"

