---
- name: Run ElasticSearch
  docker_container:
    name: "{{ es_container_name }}"
    image: "{{ es_image }}"
    state: started
    networks:
      - name: "{{ network_name }}"
    ulimits:
      - 'memlock:-1:-1'

    env:
      ES_JAVA_OPTS: "-Xms{{es_memory}} -Xmx{{es_memory}}"

    volumes:
      - "{{es_volume}}:/usr/share/elasticsearch/data"
      - "{{configuration_dir}}/es/keys/root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem"

      - "{{configuration_dir}}/es/keys/node-1.pem:/usr/share/elasticsearch/config/node-1.pem"
      - "{{configuration_dir}}/es/keys/node-1-key.pem:/usr/share/elasticsearch/config/node-1-key.pem"

      - "{{configuration_dir}}/es/keys/admin.pem:/usr/share/elasticsearch/config/admin.pem"
      - "{{configuration_dir}}/es/keys/admin-key.pem:/usr/share/elasticsearch/config/admin-key.pem"

      - "{{configuration_dir}}/es/elasticsearch-secured.yml:/usr/share/elasticsearch/config/elasticsearch.yml"

      - "{{configuration_dir}}/es/internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml"
      - "{{configuration_dir}}/es/opendistro-config.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml"
  register: elastic_output

- name: Permission to execute securityadmin for Elastic Search
  command: "docker exec {{ es_container_name }} chmod +x 'plugins/opendistro_security/tools/securityadmin.sh'"

- name: Run securityadmin to initialize Open Distro Security
  command: "docker exec {{ es_container_name }} plugins/opendistro_security/tools/securityadmin.sh -cd plugins/opendistro_security/securityconfig/ -cacert config/root-ca.pem -cert config/admin.pem -key config/admin-key.pem -icl -nhnv"
  when: elastic_output.changed
  register: securityadmin_result
  until: securityadmin_result.rc == 0
  retries: 10
  delay: 2

- name: Set the default template to 1 shard and 0 replicas per index
  command: "docker exec {{ es_container_name}} curl -XPOST -k -H \"Content-type: application/json\" \"https://admin:ChangemePlse@elastic_service:9200/_template/default\" -d '{\"template\": \"*\", \"order\": -1, \"settings\": { \"number_of_shards\": \"1\", \"number_of_replicas\": \"0\"}}'"
