---

- name: Check Kibana Running
  uri:
    url: "http://{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}:{{kibana_port}}"
    method: GET
  register: check_kibana
  failed_when: false


- name: Run Kibana
  docker_container:
    name: "{{ kibana_container_name }}"
    image: "{{ kibana_image }}"
    state: started
    restart: "{{ 'yes' if check_kibana.status != 200 else 'no'}}"
    networks:
      - name: "{{ network_name }}"
    ports:
      - "{{ kibana_port }}:5601"
    volumes:
      - "{{configuration_dir}}/es/keys/kibana.pem:/usr/share/kibana/config/kibana.pem"
      - "{{configuration_dir}}/es/keys/kibana-key.pem:/usr/share/kibana/config/kibana-key.pem"
      - "{{configuration_dir}}/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml"
      - "{{configuration_dir}}/es/keys/root-ca.pem:/usr/share/kibana/config/root-ca.pem"

- name: Wait for Kibana Running
  wait_for:
    port: '{{kibana_port}}'
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
