---

- name: Check ElasticSearch Running
  uri:
    url: "https://{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}:{{es_port}}/_cluster/health"
    method: GET
    user: admin
    password: "{{es_admin_password}}"
    force_basic_auth: yes
    validate_certs: no
  register: check_es
  failed_when: false


- name: Run ElasticSearch
  docker_container:
    name: "{{ es_container_name }}"
    image: "{{ es_image }}"
    state: started
    restart: "{{'yes' if check_es.status != 200 or (check_es.json.status != 'yellow' and check_es.json.status != 'green' ) else 'no'}}"
    networks:
      - name: "{{ network_name }}"
    ports:
      - "{{ es_port }}:9200"
      - "9600:9600" # required for Performance Analyzer
    ulimits:
      - 'memlock:-1:-1'

    env:
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"

    volumes:
      # - "/tmp/es-data:/usr/share/elasticsearch/data"
      - "{{configuration_dir}}/es/keys/root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem"

      - "{{configuration_dir}}/es/keys/node-1.pem:/usr/share/elasticsearch/config/node-1.pem"
      - "{{configuration_dir}}/es/keys/node-1-key.pem:/usr/share/elasticsearch/config/node-1-key.pem"

      - "{{configuration_dir}}/es/keys/admin.pem:/usr/share/elasticsearch/config/admin.pem"
      - "{{configuration_dir}}/es/keys/admin-key.pem:/usr/share/elasticsearch/config/admin-key.pem"

      - "{{configuration_dir}}/es/elasticsearch-secured.yml:/usr/share/elasticsearch/config/elasticsearch.yml"

      - "{{configuration_dir}}/es/internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml"


- name: Wait for Elasticsearch 9200 Open
  wait_for:
    port: '{{es_port}}'
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'



- name: Permission to execute securityadmin for Elastic Search
  command: "docker exec elastic_service chmod +x 'plugins/opendistro_security/tools/securityadmin.sh'"

- name: Run securityadmin to initialize Open Distro Security
  command: "docker exec elastic_service plugins/opendistro_security/tools/securityadmin.sh -cd plugins/opendistro_security/securityconfig/ -cacert config/root-ca.pem -cert config/admin.pem -key config/admin-key.pem -icl -nhnv"
  register: securityadmin_result
  until: securityadmin_result.rc == 0
  retries: 10
  delay: 2
