---

- name: Run worker {{worker_id}}
  vars:
    docker_worker_name: "{{mordred_name}}_{{worker_id}}"
  docker_container:
    name: "{{ docker_worker_name }}"
    image: "{{ mordred_image }}"
    state: started
    networks:
      - name: "{{ network_name }}"
    env:
      WORKER_NAME: "{{ docker_worker_name }}"
    volumes:
      - "{{configuration_dir}}/mordred/worker_config.py:/code/mordred/MordredManager/config.py"
      - "{{configuration_dir}}/mordred/setup-default.cfg:/code/mordred/MordredManager/mordred/setup-default.cfg"
      - "{{volume_name}}:/dashboard_logs"
