---

- name: Wait for Kibana Running
  uri:
    url: "https://{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}:{{app_port}}/kibana"
    method: GET
    validate_certs: no
  register: result
  until: result.status == 200
  retries: 10
  delay: 5

- name: Delete panels container if it was created
  docker_container:
    name: "{{panels_container}}"
    state: absent
    stop_timeout: 10

- name: Import default panels (may take some time)
  docker_container:
    name: "{{panels_container}}"
    image: "{{panels_image}}"
    state: started
    detach: no
    networks:
      - name: "{{ network_name }}"
    volumes:
      - "{{configuration_dir}}/archimedes_panels/settings.py:/settings.py"

