---
- name: Check if database {{db_django_name}} is running
  shell: "docker run --rm --network {{network_name}} mysql sh -c 'mysql -h {{db_container_name}} -u {{db_user}} -p{{db_password}} -D {{db_django_name}}'"
  register: check_db
  failed_when: false

- name: Run database
  docker_container:
    name: "{{ db_container_name }}"
    image: "{{ db_image }}"
    restart: "{{ 'yes' if check_db.rc != 0 else 'no'}}"
    state: started
    networks:
      - name: "{{ network_name }}"
    ports:
      - "{{ db_port }}:3306"
    volumes:
      - "{{configuration_dir}}/database:/docker-entrypoint-initdb.d"
      #- "{{configuration_dir}}/db_data:/var/lib/mysql"
