---
## Build Cauldron poolscheduler image
##
## For this playbook to work, ensure docker-py is installed
##

- name: "Ensures {{ WORKER_IMAGE_BUILD_DIR }} exists"
  file:
    path: "{{ WORKER_IMAGE_BUILD_DIR }}"
    state: directory
  tags: [worker]

- name: "Copy source code from {{ WORKER_IMAGE_LOCAL_CODE | default('\"undefined\"') }} to {{ WORKER_IMAGE_BUILD_DIR }}/"
  synchronize:
    src: "{{ WORKER_IMAGE_LOCAL_CODE }}/"
    dest: "{{ WORKER_IMAGE_BUILD_DIR }}/"
    recursive: yes
    delete: yes
  when: 'WORKER_IMAGE_LOCAL_CODE is defined'
  tags: [worker]

- name: "Clone source code from {{ WORKER_IMAGE_GIT_CODE  | default('\"undefined\"') }} to {{ WORKER_IMAGE_BUILD_DIR }}/"
  git:
    repo: "{{ WORKER_IMAGE_GIT_CODE }}"
    dest: "{{ WORKER_IMAGE_BUILD_DIR }}/"
    version: "{{ WORKER_IMAGE_GIT_VERSION }}"
  when: 'WORKER_IMAGE_LOCAL_CODE is not defined'
  tags: [worker]

- name: "Build the image for Cauldron worker"
  docker_image:
    name: "{{ WORKER_IMAGE_NAME }}"
    build:
      path: "{{ WORKER_IMAGE_BUILD_DIR }}/"
      dockerfile: "{{ WORKER_IMAGE_BUILD_DIR }}/docker/Dockerfile"
      pull: "no"
    source: build
    state: present
  tags: [worker]
