---

- name: Run worker {{worker_id}}
  vars:
    docker_worker_name: "{{WORKER_CONTAINER_NAME}}_{{worker_id}}"
    worker_volumes:
      - "{{PROJECT_LOGS_MOUNT_POINT}}:/job_logs"
      - "{{PERCEVAL_REPOS_MOUNT_POINT}}:/git_repositories"
    dev_volumes:
      - "{{DEV_WORKER_REPOSITORY}}:/code"
      - "{{DEV_POOLSCHED_REPOSITORY}}/poolsched:/code/poolsched_worker/poolsched"
      - "{{DEV_COMMON_APPS_REPOSITORY}}/cauldron_apps:/code/poolsched_worker/cauldron_apps"
  docker_container:
    name: "{{ docker_worker_name }}"
    image: "{{ WORKER_IMAGE_NAME }}"
    restart_policy: "on-failure"
    restart_retries: 5
    state: started
    networks:
      - name: "{{ NETWORK_NAME }}"
    env:
      WORKER_NAME: "{{ docker_worker_name }}"
      DB_HOST: "{{ DB_HOST }}"
      DB_USER: "{{ DB_USER }}"
      DB_PASSWORD: "{{ DB_USER_PASSWORD }}"
      DB_NAME: "{{ DB_DJANGO_NAME }}"
      DB_PORT: "{{ DB_PORT }}"
      GIT_REPOS: "/git_repositories"
      JOB_LOGS: "/job_logs"
      ELASTIC_USER: "admin"
      ELASTIC_PASS: "{{ ELASTIC_ADMIN_PASSWORD }}"
      ELASTIC_HOST: "{{ ELASTIC_HOST }}"
      ELASTIC_PORT: "{{ ELASTIC_PORT }}"
    volumes: '{{worker_volumes + dev_volumes if DEV_ENABLED else worker_volumes}}'
  tags: [worker]
