---

- name: Run backup rotation image (create and remove snapshots)
  docker_container:
    name: "{{ BACKUP_CONTAINER_NAME }}"
    image: "{{ BACKUP_IMAGE_NAME }}"
    state: started
    restart_policy: "on-failure"
    networks:
      - name: "{{ NETWORK_NAME }}"
    env:
      LOCAL_BACKUP: "{{ 1 if LOCAL_BACKUP_ENABLED else '' }}"
      S3_BACKUP: "{{ 1 if S3_BACKUP_ENABLED else '' }}"
      ODFE_ADMIN_PASSWORD: "{{ ELASTIC_ADMIN_PASSWORD }}"
      ODFE_HOST: "{{ ELASTIC_HOST }}"
      ODFE_LOCAL_SNAPSHOT_REPO: "cauldron_backup"
      ODFE_S3_SNAPSHOT_REPO: "s3_repository"
      DB_PASSWORD: "{{ DB_USER_PASSWORD }}"
      DB_HOST: "{{ DB_HOST }}"
      S3_ENDPOINT: "{{ BACKUP_S3_ENDPOINT }}"
      S3_BUCKET: "{{ BACKUP_S3_BUCKET }}"
      S3_PATH: "{{ BACKUP_S3_PATH }}"
      S3_ACCESS_KEY: "{{ BACKUP_S3_ACCESS_KEY }}"
      S3_SECRET_KEY: "{{ BACKUP_S3_SECRET_KEY }}"
    volumes:
      - "{{MYSQLDUMP_MOUNT_POINT}}:/mysqldump"
  tags: [backups]
