---

- name: Run Kibana
  docker_container:
    name: "{{ KIBANA_CONTAINER_NAME }}"
    image: "{{ KIBANA_IMAGE_NAME }}"
    state: started
    restart_policy: "always"
    networks:
      - name: "{{ NETWORK_NAME }}"
    volumes:
      - "{{CAULDRON_CONFIG_DIR}}/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml"
      - "{{CAULDRON_CONFIG_DIR}}/es/keys/root-ca.pem:/usr/share/kibana/config/root-ca.pem"
  tags: [kibana]
