---
- name: Create {{configuration_dir}}/es dir if not exists
  file: path={{configuration_dir}}/es state=directory

- name: Create {{configuration_dir}}/kibana dir if not exists
  file: path={{configuration_dir}}/kibana state=directory

- name: Copy keys for Elasticseach and kibana
  copy:
    src: "keys"
    dest: "{{ configuration_dir }}/es/"
    mode: 0644


- name: Create ElasticSearch global configuration
  template:
    src: elasticsearch-secured.yml.j2
    dest: "{{ configuration_dir }}/es/elasticsearch-secured.yml"
    mode: 0644


- name: Create ElasticSearch security configuration
  template:
    src: opendistro-config.yml.j2
    dest: "{{ configuration_dir }}/es/opendistro-config.yml"
    mode: 0644


- name: Create Kibana configuration
  template:
    src: kibana.yml.j2
    dest: "{{ configuration_dir }}/kibana/kibana.yml"
    mode: 0644


- name: Create hashes for elasticsearch passwords
  include: hash_password.yml
  with_items:
      - { loop_psw: "{{ es_admin_password }}", loop_output: "hash_es_admin_password" }
      - { loop_psw: "{{ es_logstash_password }}", loop_output: "hash_es_logstash_password" }
      - { loop_psw: "{{ es_kibanaserver_password }}", loop_output: "hash_es_kibanaserver_password" }
      - { loop_psw: "{{ es_kibanaro_password }}", loop_output: "hash_es_kibanaro_password" }
      - { loop_psw: "{{ es_readall_password }}", loop_output: "hash_es_readall_password" }
      - { loop_psw: "{{ es_snapshotrestore_password }}", loop_output: "hash_es_snapshotrestore_password" }


- name: Copy Elasticsearch internal_users.yml configuration
  template:
    src: internal_users.yml.j2
    dest: "{{ configuration_dir }}/es/internal_users.yml"
    mode: 0644
