---

- name: Generate django secret key
  command: openssl rand -base64 32
  register: django_key

- name: Create {{configuration_dir}}/django dir if not exists
  file: path={{configuration_dir}}/django state=directory

- name: Configure django settings
  template:
    src: django_settings.py.j2
    dest: "{{ configuration_dir }}/django/django_settings.py"
