---

- name: Generate django secret key
  command: openssl rand -base64 32
  register: django_key

- name: Ensures {{configuration_dir}}/django dir exists
  file: path={{configuration_dir}}/django state=directory

- name: Configure django settings
  template:
    src: django_settings.py.j2
    dest: "{{ configuration_dir }}/django/django_settings.py"

- name: Copy the private key for JWT
  copy:
    src: "django/jwtR256.key"
    dest: "{{ configuration_dir }}/django/jwtR256.key"
    mode: "0600"
