---

# @action configure_django.yml # Create a secret key for Django.
- name: Generate django secret key
  command: openssl rand -base64 32
  register: django_key

# @action configure_django.yml # Create `<configuration_dir>/django` directory if not exists.
# @var configuration_dir: /tmp # Main configuration directory.
- name: Create {{configuration_dir}}/django dir if not exists
  file: path={{configuration_dir}}/django state=directory

# @action configure_django.yml # Copy the file `django_settings.py.j2` to `<configuration_dir>/django/django_settings.py`
# @var configuration_dir: /tmp # Main configuration directory.
- name: Configure django settings
  template:
    src: django_settings.py.j2
    dest: "{{ configuration_dir }}/django/django_settings.py"
