---

- name: Generate passwords for {{item.loop_output}} and get result
  docker_container:
    name: "{{passwords_container}}"
    image: "{{es_image}}"
    cleanup : yes
    detach: no
    entrypoint: "/bin/bash"
    command: "/usr/share/elasticsearch/plugins/opendistro_security/tools/hash.sh -p {{item.loop_psw}}"
  register: output

- set_fact:
    "{{ item.loop_output }}": "{{ output.ansible_facts.docker_container.Output }}"