---
- name: Create a network for cauldron
  import_tasks: create_network.yml

- name: Create a volume for cauldron
  import_tasks: create_volume.yml

- name: Configure django
  import_tasks: configure_django.yml

- name: Build django image
  import_tasks: build_django.yml

- name: Configure mordred
  import_tasks: configure_many_mordred.yml

- name: Build mordred image
  import_tasks: build_mordred.yml

- name: Build database image
  import_tasks: build_database.yml

- name: Configure database
  import_tasks: configure_database.yml

- name: Configure Opendistro
  import_tasks: configure_opendistro.yml

- name: Pull mysql for checks
  import_tasks: pull_mysql.yml

- name: Copy panels
  import_tasks: copy_panels.yml