---
## Build Cauldron webserver image
##
## For this playbook to work, ensure docker-py is installed
##


- name: "Ensures {{ WEB_IMAGE_BUILD_DIR }} exists"
  file:
    path: "{{ WEB_IMAGE_BUILD_DIR }}"
    state: directory
  tags: [webserver]

- name: "Copy source code from {{ WEB_IMAGE_LOCAL_CODE | default('\"undefined\"') }} to {{ WEB_IMAGE_BUILD_DIR }}/"
  synchronize:
    src: "{{ WEB_IMAGE_LOCAL_CODE }}/"
    dest: "{{ WEB_IMAGE_BUILD_DIR }}/"
    recursive: yes
    delete: yes
  when: 'WEB_IMAGE_LOCAL_CODE is defined'
  tags: [webserver]

- name: "Clone source code from {{ WEB_IMAGE_GIT_CODE  | default('\"undefined\"') }} to {{ WEB_IMAGE_BUILD_DIR }}/"
  git:
    repo: "{{ WEB_IMAGE_GIT_CODE }}"
    dest: "{{ WEB_IMAGE_BUILD_DIR }}/"
    version: "{{ WEB_IMAGE_GIT_VERSION }}"
  when: 'WEB_IMAGE_LOCAL_CODE is not defined'
  tags: [webserver]

- name: "Build the image for Cauldron webserver"
  docker_image:
    name: "{{ WEB_IMAGE_NAME }}"
    build:
      path: "{{ WEB_IMAGE_BUILD_DIR }}/"
      dockerfile: "{{ WEB_IMAGE_BUILD_DIR }}/docker/Dockerfile"
      pull: "no"
    source: build
    state: present
  tags: [webserver]
