---

- name: "Ensures {{CAULDRON_CONFIG_DIR}}/django dir exists"
  file:
    path: "{{CAULDRON_CONFIG_DIR}}/django"
    state: directory
    recurse: yes
  tags: [webserver]


- name: "Copy JWT private key for Cauldron"
  synchronize:
    src: "{{ inventory_hostname }}/jwt_key/jwtR256.key"
    dest: "{{ CAULDRON_CONFIG_DIR }}/django/jwtR256.key"
  tags: [webserver]

- name: "Copy custom files for Cauldron"
  synchronize:
    src: "{{inventory_hostname}}/cauldron_custom/"
    dest: "{{ CAULDRON_CONFIG_DIR }}/django/cauldron_custom"
    recursive: yes
    delete: yes
  tags: [webserver]


- name: Django Secret Key for settings.py
  command: openssl rand -base64 32
  register: django_secret_key
  tags: [webserver]
