---

WEB_CONTAINER_NAME: "cauldron_service"

DJANGO_DEBUG: 'True'

CAULDRON_CONFIG_DIR: "/tmp/webserver"
WEB_IMAGE_NAME: "cauldron2-webserver:test"
WEB_IMAGE_DOCKERFILE_PATH: "../docker/webserver/"
WEB_IMAGE_BUILD_DIR: "{{ CAULDRON_CONFIG_DIR }}/webserver-build"
WEB_IMAGE_GIT_CODE: "https://gitlab.com/cauldron2/cauldron-web"
WEB_IMAGE_GIT_VERSION: "master"


DB_USER: "grimoirelab"
DB_DJANGO_NAME: "db_cauldron"
DB_PORT: "3306"
ELASTIC_PROTOCOL: "https"
ELASTIC_PORT: '9200'
KIBANA_PROTOCOL: 'http'
KIBANA_PORT: '5601'
KIBANA_URL_PATH: '/kibana'