---

DJANGO_DEBUG: 'True'

CAULDRON_CONFIG_DIR: "/tmp/webserver"
WEB_IMAGE_NAME: "cauldronio-webserver:test"
WEB_IMAGE_BUILD_DIR: "{{ CAULDRON_CONFIG_DIR }}/webserver-build"
WEB_IMAGE_GIT_CODE: "https://gitlab.com/cauldronio/cauldron-web"
WEB_IMAGE_GIT_VERSION: "master"
WEB_PORT: '8000'


DB_USER: "grimoirelab"
DB_DJANGO_NAME: "db_cauldron"
DB_PORT: "3306"
ELASTIC_PROTOCOL: "https"
ELASTIC_PORT: '9200'
KIBANA_PROTOCOL: 'http'
KIBANA_PORT: '5601'
KIBANA_URL_PATH: '/kibana'

WEB_EXPORTED_PORTS: "{{WEB_HOST}}:{{WEB_PORT}}:{{WEB_PORT}}"
