---
- hosts: localhost
  remote_user: root
  tasks:
    - name: Build Django Docker image
      command: docker build -t cauldron https://gitlab.com/cauldron2/deployment.git#:cauldron

    - name: Build Mordred Docker image
      command: docker build -t mordred https://gitlab.com/cauldron2/deployment.git#:mordred
