---

- hosts: webserver
  tasks:
  - include_role:
      name: database
      tasks_from: setup
    tags: [database]

  - include_role:
      name: kibana
      tasks_from: setup
    tags: [kibana]

  - include_role:
      name: nginx
      tasks_from: setup
    tags: [nginx]

  - include_role:
      name: syslog
      tasks_from: setup
    tags: [syslog]

  - include_role:
      name: matomo
      tasks_from: setup
    tags: [matomo]

  - include_role:
      name: webserver
      tasks_from: setup
    tags: [webserver]

  - include_role:
      name: workers
      tasks_from: setup
    tags: [worker]

  - include_role:
      name: odfe-config
      tasks_from: setup
    tags: [odfe-config]

  - include_role:
      name: hatstall
      tasks_from: setup
    when: HATSTALL_ENABLED
    tags: [hatstall]

- hosts: elasticsearch
  tasks:
  - include_role:
      name: elasticsearch
      tasks_from: setup
    tags: [elastic]
