---

- hosts: all
  tasks:
  - include_role:
      name: common
      tasks_from: create_JWT_key.yml
    tags: [elastic, webserver]

  - include_role:
      name: database
      tasks_from: setup
    tags: [database]

  - include_role:
      name: elasticsearch
      tasks_from: setup
    tags: [elastic]

  - include_role:
      name: kibana
      tasks_from: setup
    tags: [kibana]

  - include_role:
      name: nginx
      tasks_from: setup
    tags: [nginx]

  - include_role:
      name: webserver
      tasks_from: setup
    tags: [webserver]

  - include_role:
      name: workers
      tasks_from: setup
    tags: [worker]

  - include_role:
      name: panels
      tasks_from: setup
    tags: [panels]

  - include_role:
      name: hatstall
      tasks_from: setup
    when: HATSTALL_ENABLED
    tags: [hatstall]

