---

- hosts: cauldron_group
  tasks:
  - include_role:
      name: webserver
      tasks_from: remove
    tags: [webserver]

  - include_role:
      name: schedworkers
      tasks_from: remove
    tags: [worker]

- hosts: elastic_group
  tasks:
  - include_role:
      name: elasticsearch
      tasks_from: remove
    tags: [elastic]

- hosts: database_group
  tasks:
  - include_role:
      name: database
      tasks_from: remove
    tags: [database]

  - include_role:
      name: kibana
      tasks_from: remove
    tags: [kibana]

  - include_role:
      name: nginx
      tasks_from: remove
    tags: [nginx]

  - include_role:
      name: syslog
      tasks_from: remove
    tags: [syslog]

  - include_role:
      name: matomo
      tasks_from: remove
    tags: [matomo]

  - include_role:
      name: backup-rotate
      tasks_from: remove
    tags: [backups]

  - include_role:
      name: pa-to-es
      tasks_from: remove
    when: PA_TO_ES_ENABLED
    tags: [pa-to-es]
