---

- hosts: cauldron_group
  tasks:
    - name: "Delete webserver image"
      docker_image:
        state: absent
        name: "{{ WEB_IMAGE_NAME }}"
      tags: [webserver]

    - name: "Delete worker image"
      docker_image:
        state: absent
        name: "{{ WORKER_IMAGE_NAME }}"
      tags: [worker]

- hosts: elastic_group
  tasks:
    - name: "Delete elasticsearch image"
      docker_image:
        state: absent
        name: "{{ ELASTIC_IMAGE_NAME }}"
      tags: [elastic]

- hosts: database_group
  tasks:
    - name: "Delete database image"
      docker_image:
        state: absent
        name: "{{ DB_IMAGE_NAME }}"
      tags: [database]

    - name: "Delete kibana image"
      docker_image:
        state: absent
        name: "{{ KIBANA_IMAGE_NAME }}"
      tags: [kibana]

    - name: "Delete odfe config image"
      docker_image:
        state: absent
        name: "{{ ODFE_CONFIG_IMAGE_NAME }}"
      tags: [odfe-config]

    - name: "Delete syslog image"
      docker_image:
        state: absent
        name: "{{ SYSLOG_IMAGE_NAME }}"
      tags: [syslog]

    - name: "Delete pa-to-es image"
      docker_image:
        state: absent
        name: "{{ PA_TO_ES_IMAGE_NAME }}"
      when: PA_TO_ES_ENABLED
      tags: [pa-to-es]

    - name: "Delete backup-rotate image"
      docker_image:
        state: absent
        name: "{{ BACKUP_IMAGE_NAME }}"
      tags: [backups]

