---
- hosts: all
  tasks:
  - name: "Remove Logs volume: {{ LOGS_MOUNT_POINT }}"
    docker_volume:
      name: "{{ LOGS_MOUNT_POINT }}"
      state: absent
    tags: [logs]

  - name: "Remove Elasticsearch volume: {{ ELASTIC_MOUNT_POINT }}"
    docker_volume:
      name: "{{ ELASTIC_MOUNT_POINT }}"
      state: absent
    tags: [elastic]

  - name: "Remove Database volume: {{ DB_MOUNT_POINT }}"
    docker_volume:
      name: "{{ DB_MOUNT_POINT }}"
      state: absent
    tags: [database]

  - name: "Remove Git Perceval Repositories volume: {{PERCEVAL_REPOS_MOUNT_POINT}}"
    docker_volume:
      name: "{{ PERCEVAL_REPOS_MOUNT_POINT }}"
      state: absent
    tags: [worker]