---
- hosts: all
  tasks:
  - name: "Remove Projects logs volume: {{ PROJECT_LOGS_MOUNT_POINT }}"
    docker_volume:
      name: "{{ PROJECT_LOGS_MOUNT_POINT }}"
      state: absent
    tags: [project_logs]

  - name: "Remove Elasticsearch volume: {{ ELASTIC_MOUNT_POINT }}"
    docker_volume:
      name: "{{ ELASTIC_MOUNT_POINT }}"
      state: absent
    tags: [elastic]

  - name: "Remove Elasticsearch snapshots volume: {{ ELASTIC_SNAPSHOT_MOUNT_POINT }}"
    docker_volume:
      name: "{{ ELASTIC_SNAPSHOT_MOUNT_POINT }}"
      state: absent
    tags: [elastic_snapshot]

  - name: "Remove Database volume: {{ DB_MOUNT_POINT }}"
    docker_volume:
      name: "{{ DB_MOUNT_POINT }}"
      state: absent
    tags: [database]

  - name: "Remove NGINX logs: {{ NGINX_LOGS_MOUNT_POINT }}"
    docker_volume:
      name: "{{ NGINX_LOGS_MOUNT_POINT }}"
      state: absent
    tags: [nginx]

  - name: "Remove Git Perceval Repositories volume: {{PERCEVAL_REPOS_MOUNT_POINT}}"
    docker_volume:
      name: "{{ PERCEVAL_REPOS_MOUNT_POINT }}"
      state: absent
    tags: [repositories]

  - name: "Remove syslog volume: {{SYSLOG_MOUNT_POINT}}"
    docker_volume:
      name: "{{ SYSLOG_MOUNT_POINT }}"
      state: absent
    tags: [syslog]
