---
# Remove Django and Elasticsearch volumes
# Warning: this will delete all data (indexes, configuration,
#   users, permissions, etc.) in Cauldron!!!!!!
# Usually run after stop_cauldron.yml, if you want all
#   persistent databases to be emptied, to start from scratch.

- hosts: all
  tasks:
    - name: "Remove Django volume: {{ volume_name }}"
      docker_volume:
        name: "{{ volume_name }}"
        state: absent

    - name: "Remove Elasticsearch volume: {{ es_volume }}"
      docker_volume:
        name: "{{ es_volume }}"
        state: absent
