---

ODFE_CONFIG_CONTAINER_NAME: "odfe_config_cauldron"

CAULDRON_CONFIG_DIR: "/tmp/cauldron"
ODFE_CONFIG_IMAGE_NAME: "cauldronio-odfe-config:test"
ODFE_CONFIG_IMAGE_DOCKERFILE_PATH: "../docker/odfe-config/"
ODFE_CONFIG_IMAGE_BUILD_DIR: "{{ CAULDRON_CONFIG_DIR }}/odfe-config-build"

ELASTIC_PROTOCOL: "https"
ELASTIC_PORT: '9200'
KIBANA_PROTOCOL: 'http'
KIBANA_PORT: '5601'
KIBANA_URL_PATH: '/kibana'
