---
- name: Stop and remove Kibana container
  docker_container:
    name: "{{kibana_container_name}}"
    state: absent
    stop_timeout: 10

- name: Delete Kibana image
  docker_image:
    name: "{{kibana_image}}"
    state: absent
