---

- name: Remove database files
  file:
    state: absent
    path: "{{configuration_dir}}/database"

- name: Remove django files
  file:
    state: absent
    path: "{{configuration_dir}}/django"

- name: Remove Kibana files
  file:
    state: absent
    path: "{{configuration_dir}}/kibana"

- name: Remove ES files
  file:
    state: absent
    path: "{{configuration_dir}}/es"

- name: Remove Panels files
  file:
    state: absent
    path: "{{ configuration_dir }}/panels"

- name: Remove Mordred files
  file:
    state: absent
    path: "{{ configuration_dir }}/mordred"

- name: Remove Panels files
  file:
    state: absent
    path: "{{ configuration_dir }}/archimedes_panels"

- name: Remove Nginx files
  file:
    state: absent
    path: "{{ configuration_dir }}/nginx"
